apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyoezer
  namespace: kinley
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kyoezer
  template:
    metadata:
      labels:
        app: kyoezer
    spec:
      containers:
        - name: kyoezer
          image: quay.io/pandeysp/nginxdemo
          ports:
            - containerPort: 80
